# Kubernetes - FLASKAPI-BACKEND - ServiceMonitor Definition Manifest file
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flaskapi-backend-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus   
spec:
  namespaceSelector:
    matchNames:
      - webapp
  selector:
    matchLabels:
      app: flaskapi-backend
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
